# Header: E.g. Introduction

Here we can write some description for the notebook.

# Import packages

In [1]:
import scanpy

In [2]:
import scanpy as sc

In [3]:
import scanpy as sc
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy

# Common data types in Python

## Integer

In [4]:
x = 1

In [5]:
print(x)

1


In [6]:
type(x)

int

## String

In [7]:
y = 'test'

In [8]:
print(y)

test


In [9]:
type(y)

str

In [10]:
z = "test1"

In [11]:
print(z)

test1


In [12]:
type(z)

str

## List

In [16]:
a = [0, 1, 2, 'test']

In [17]:
print(a)

[0, 1, 2, 'test']


In [18]:
type(a)

list

In [19]:
b = [1, 2, [0, -1, 2], 'test', 'example']
print(b)
print(type(b))

[1, 2, [0, -1, 2], 'test', 'example']
<class 'list'>


## Numpy arrays

### Two dimensional arrays

In [20]:
arr = np.array([[0, 1, 0], [0, 1, 2], [2, 1, 0]])

In [21]:
arr

array([[0, 1, 0],
       [0, 1, 2],
       [2, 1, 0]])

In [22]:
print(arr)

[[0 1 0]
 [0 1 2]
 [2 1 0]]


In [23]:
type(arr)

numpy.ndarray

### One dimensional array

In [24]:
b = np.array([-1, 0, 2])

In [25]:
b

array([-1,  0,  2])

In [26]:
type(b)

numpy.ndarray

## Sparse arrays

In [27]:
example_array = np.array([[0, 0, 1], [0, 1, 0], [2, 0, 0]])
example_array

array([[0, 0, 1],
       [0, 1, 0],
       [2, 0, 0]])

In [28]:
example_sp = scipy.sparse.csr_matrix(example_array)

In [29]:
example_sp

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>

## Pandas dataframe

In [30]:
example_df = pd.DataFrame(index = ['Cell-0', 'Cell-1', 'Cell-2'], 
                          columns = ['Gene-A', 'Gene-B'], 
                          data = [[0, 1], [2, 0], [1, 1]])

In [31]:
example_df

Gene-A  Gene-B
Cell-0       0       1
Cell-1       2       0
Cell-2       1       1

In [32]:
example_df.loc['Cell-0']

Gene-A    0
Gene-B    1
Name: Cell-0, dtype: int64

In [33]:
example_df['Gene-A']

Cell-0    0
Cell-1    2
Cell-2    1
Name: Gene-A, dtype: int64

### Define dataframe through arrays

In [34]:
example_array = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']])
example_array

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U1')

In [35]:
example_df2 = pd.DataFrame(example_array)

In [36]:
example_df2

0  1  2
0  A  B  C
1  D  E  F
2  G  H  I

In [37]:
example_df2.index = ['Q0', 'Q1', 'Q2']

In [38]:
example_df2.columns = ['W0', 'W1', 'W2']

In [39]:
example_df2

W0 W1 W2
Q0  A  B  C
Q1  D  E  F
Q2  G  H  I

## Dictionary

In [40]:
dictionary_example1 = {'key1' : 'value1', 'key2': 'value2'}

In [41]:
dictionary_example1['key1']

'value1'

In [42]:
dictionary_example1['key2']

'value2'

In [43]:
dictionary_example1 = {'Gene program-1': ['Gene-A', 'Gene-B', 'Gene-C'], 
                       'Gene program-2': ['Gene-C', 'Gene-D']}
dictionary_example1['Gene program-3'] = ['Gene-E', 'Gene-A']

In [44]:
dictionary_example1['Gene program-2']

['Gene-C', 'Gene-D']

# AnnData

In [49]:
adata = sc.read_10x_h5('/Users/sharmar1/Dropbox/msk_workshop/SCALE_2024_winter/scale_2024_winter_day1/data/pbmc_10k_v3_filtered_feature_bc_matrix.h5')

/Users/sharmar1/opt/anaconda3/envs/workshop_2025/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/Users/sharmar1/opt/anaconda3/envs/workshop_2025/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


In [74]:
adata.var_names_make_unique()

In [75]:
adata

AnnData object with n_obs × n_vars = 11769 × 33538
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'pca'
    obsm: 'X_pca'
    varm: 'PCs'

In [51]:
adata.obs

Empty DataFrame
Columns: []
Index: [AAACCCAAGCGCCCAT-1, AAACCCAAGGTTCCGC-1, AAACCCACAGAGTTGG-1, AAACCCACAGGTATGG-1, AAACCCACATAGTCAC-1, AAACCCACATCCAATG-1, AAACCCAGTGGCTACC-1, AAACCCATCCCGAGAC-1, AAACCCATCTGGCCGA-1, AAACCCATCTGTTCAT-1, AAACGAAAGACGACGT-1, AAACGAAAGACGTCGA-1, AAACGAAAGGAGTCTG-1, AAACGAACAAGAATGT-1, AAACGAACAATACCCA-1, AAACGAACACAAGCTT-1, AAACGAACACGACGTC-1, AAACGAAGTCATGCAT-1, AAACGAAGTTATGTCG-1, AAACGAATCTACTTCA-1, AAACGCTAGACAACTA-1, AAACGCTAGAGGTTTA-1, AAACGCTAGCACCAGA-1, AAACGCTAGGCAGGTT-1, AAACGCTAGGTTAAAC-1, AAACGCTAGTATGAAC-1, AAACGCTCAATCCTAG-1, AAACGCTCACGCAAAG-1, AAACGCTCAGTCTTCC-1, AAACGCTCATAGTCAC-1, AAACGCTCATGGATCT-1, AAACGCTGTCAGACGA-1, AAACGCTGTCCCTAAA-1, AAACGCTGTCGATTTG-1, AAACGCTGTCTACATG-1, AAAGAACAGTTCCGTA-1, AAAGAACGTATCCTCC-1, AAAGAACGTATTCCGA-1, AAAGAACGTCTCGGGT-1, AAAGAACGTTTGTTGG-1, AAAGAACTCCTCCACA-1, AAAGAACTCGCGTGCA-1, AAAGAACTCTCATAGG-1, AAAGGATAGCAGTAAT-1, AAAGGATAGTGAATAC-1, AAAGGATCAAACAGGC-1, AAAGGATGTCGGTGAA-1, AAAGGATGTGTCCAAT-1, AAAGGATGTGTGGTCC-1, AAAGGATTCAAGGACG-1, AAAGGATTCATTGTTC-1, AAAGGATTCCTAACAG-1, AAAGGATTCGTAACAC-1, AAAGGATTCTGCGGGT-1, AAAGGATTCTTTGCAT-1, AAAGGGCAGGGACCAT-1, AAAGGGCAGTTCCGGC-1, AAAGGGCCACGTCGTG-1, AAAGGGCCAGGTTCGC-1, AAAGGGCCATCATCCC-1, AAAGGGCGTTACGTAC-1, AAAGGGCTCATTTGGG-1, AAAGGGCTCCAACTGA-1, AAAGGGCTCCTGGGAC-1, AAAGGGCTCTCAAAGC-1, AAAGGGCTCTTCCACG-1, AAAGGTAAGGGTCACA-1, AAAGGTACAAGAATGT-1, AAAGGTACAGCTACAT-1, AAAGGTAGTATTTCTC-1, AAAGGTAGTCTACACA-1, AAAGGTAGTGCTATTG-1, AAAGGTAGTTAAGGAT-1, AAAGGTAGTTGTCATG-1, AAAGGTATCATAGAGA-1, AAAGGTATCGCAGAGA-1, AAAGTCCAGACCAAGC-1, AAAGTCCAGCAGGCTA-1, AAAGTCCAGTCACACT-1, AAAGTCCCAAGCTGTT-1, AAAGTCCCAAGTGGTG-1, AAAGTCCGTCGAAACG-1, AAAGTCCGTTCCCACT-1, AAAGTCCGTTCGGTTA-1, AAAGTCCTCAACTACG-1, AAAGTCCTCAGCGGAA-1, AAAGTCCTCCAAGGGA-1, AAAGTCCTCTGGGTCG-1, AAAGTGAAGAGTGGCT-1, AAAGTGAAGCATGATA-1, AAAGTGAAGCGGGTAT-1, AAAGTGAAGGTACATA-1, AAAGTGACAGATCCTA-1, AAAGTGACATAGGTTC-1, AAAGTGACATCGAACT-1, AAAGTGACATGACGGA-1, AAAGTGACATGCAGCC-1, AAAGTGAGTACCGTCG-1, AAAGTGAGTTAAGACA-1, AAAGTGATCAATGTCG-1, ...]

[11769 rows x 0 columns]

In [52]:
type(adata.obs)

pandas.core.frame.DataFrame

In [53]:
adata.var

gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC233755.2   ENSG00000277856  Gene Expression  GRCh38
AC233755.1   ENSG00000275063  Gene Expression  GRCh38
AC240274.1   ENSG00000271254  Gene Expression  GRCh38
AC213203.1   ENSG00000277475  Gene Expression  GRCh38
FAM231C      ENSG00000268674  Gene Expression  GRCh38

[33538 rows x 3 columns]

In [54]:
type(adata.var)

pandas.core.frame.DataFrame

In [55]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 24825783 stored elements and shape (11769, 33538)>

In [56]:
adata.X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [57]:
adata.X.data

array([1., 4., 2., ..., 1., 1., 1.], dtype=float32)

In [58]:
sc.pp.calculate_qc_metrics(adata, inplace=True)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [59]:
adata

AnnData object with n_obs × n_vars = 11769 × 33538
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'

In [60]:
adata.obs

n_genes_by_counts  log1p_n_genes_by_counts  total_counts  \
AAACCCAAGCGCCCAT-1               1087                 6.992096        2204.0   
AAACCCAAGGTTCCGC-1               4200                 8.343078       20090.0   
AAACCCACAGAGTTGG-1               1836                 7.515889        5884.0   
AAACCCACAGGTATGG-1               2216                 7.703910        5530.0   
AAACCCACATAGTCAC-1               1615                 7.387709        5106.0   
...                               ...                      ...           ...   
TTTGTTGGTGTCATGT-1               1331                 7.194437        3937.0   
TTTGTTGGTTTGAACC-1               1401                 7.245655        4245.0   
TTTGTTGTCCAAGCCG-1               1668                 7.419980        5602.0   
TTTGTTGTCTTACTGT-1               1745                 7.465083        6757.0   
TTTGTTGTCTTCTAAC-1                698                 6.549651        1671.0   

                    log1p_total_counts  pct_counts_in_top_50_genes  \
AAACCCAAGCGCCCAT-1            7.698483                   34.437387   
AAACCCAAGGTTCCGC-1            9.908028                   30.751618   
AAACCCACAGAGTTGG-1            8.680162                   42.641061   
AAACCCACAGGTATGG-1            8.618124                   32.839060   
AAACCCACATAGTCAC-1            8.538367                   41.676459   
...                                ...                         ...   
TTTGTTGGTGTCATGT-1            8.278428                   46.405893   
TTTGTTGGTTTGAACC-1            8.353733                   43.910483   
TTTGTTGTCCAAGCCG-1            8.631058                   45.430203   
TTTGTTGTCTTACTGT-1            8.818482                   48.068670   
TTTGTTGTCTTCTAAC-1            7.421776                   55.954518   

                    pct_counts_in_top_100_genes  pct_counts_in_top_200_genes  \
AAACCCAAGCGCCCAT-1                    44.782214                    55.716878   
AAACCCAAGGTTCCGC-1                    43.753111                    55.739174   
AAACCCACAGAGTTGG-1                    52.923182                    62.542488   
AAACCCACAGGTATGG-1                    41.681736                    51.175407   
AAACCCACATAGTCAC-1                    56.423815                    65.648257   
...                                         ...                          ...   
TTTGTTGGTGTCATGT-1                    55.956312                    65.278131   
TTTGTTGGTTTGAACC-1                    58.186101                    67.255595   
TTTGTTGTCCAAGCCG-1                    59.371653                    67.832917   
TTTGTTGTCTTACTGT-1                    63.830102                    71.496226   
TTTGTTGTCTTCTAAC-1                    61.938959                    70.197487   

                    pct_counts_in_top_500_genes  
AAACCCAAGCGCCCAT-1                    73.366606  
AAACCCAAGGTTCCGC-1                    67.819811  
AAACCCACAGAGTTGG-1                    75.254929  
AAACCCACAGGTATGG-1                    65.280289  
AAACCCACATAGTCAC-1                    78.162946  
...                                         ...  
TTTGTTGGTGTCATGT-1                    78.892558  
TTTGTTGGTTTGAACC-1                    78.775029  
TTTGTTGTCCAAGCCG-1                    79.150303  
TTTGTTGTCTTACTGT-1                    81.352671  
TTTGTTGTCTTCTAAC-1                    88.150808  

[11769 rows x 8 columns]

In [61]:
adata.var

gene_ids    feature_types  genome  n_cells_by_counts  \
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38                  0   
FAM138A      ENSG00000237613  Gene Expression  GRCh38                  0   
OR4F5        ENSG00000186092  Gene Expression  GRCh38                  0   
AL627309.1   ENSG00000238009  Gene Expression  GRCh38                 60   
AL627309.3   ENSG00000239945  Gene Expression  GRCh38                  4   
...                      ...              ...     ...                ...   
AC233755.2   ENSG00000277856  Gene Expression  GRCh38                  2   
AC233755.1   ENSG00000275063  Gene Expression  GRCh38                  2   
AC240274.1   ENSG00000271254  Gene Expression  GRCh38                101   
AC213203.1   ENSG00000277475  Gene Expression  GRCh38                  0   
FAM231C      ENSG00000268674  Gene Expression  GRCh38                  0   

             mean_counts  log1p_mean_counts  pct_dropout_by_counts  \
MIR1302-2HG     0.000000           0.000000             100.000000   
FAM138A         0.000000           0.000000             100.000000   
OR4F5           0.000000           0.000000             100.000000   
AL627309.1      0.005183           0.005170              99.490186   
AL627309.3      0.000340           0.000340              99.966012   
...                  ...                ...                    ...   
AC233755.2      0.000170           0.000170              99.983006   
AC233755.1      0.000255           0.000255              99.983006   
AC240274.1      0.008752           0.008714              99.141813   
AC213203.1      0.000000           0.000000             100.000000   
FAM231C         0.000000           0.000000             100.000000   

             total_counts  log1p_total_counts  
MIR1302-2HG           0.0            0.000000  
FAM138A               0.0            0.000000  
OR4F5                 0.0            0.000000  
AL627309.1           61.0            4.127134  
AL627309.3            4.0            1.609438  
...                   ...                 ...  
AC233755.2            2.0            1.098612  
AC233755.1            3.0            1.386294  
AC240274.1          103.0            4.644391  
AC213203.1            0.0            0.000000  
FAM231C               0.0            0.000000  

[33538 rows x 9 columns]

In [62]:
adata

AnnData object with n_obs × n_vars = 11769 × 33538
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'

In [63]:
sc.pp.normalize_total(adata)

In [64]:
adata

AnnData object with n_obs × n_vars = 11769 × 33538
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'

In [65]:
adata.X.data

array([ 2.9587114, 11.834846 ,  5.917423 , ...,  3.9024537,  3.9024537,
        3.9024537], dtype=float32)

In [66]:
sc.pp.pca(adata, n_comps = 50)

In [67]:
adata

AnnData object with n_obs × n_vars = 11769 × 33538
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'pca'
    obsm: 'X_pca'
    varm: 'PCs'

In [68]:
adata.uns['pca']

{'params': {'zero_center': True,
  'use_highly_variable': False,
  'mask_var': None},
 'variance': array([9.2077758e+04, 3.8398645e+04, 1.5128589e+04, 7.1238979e+03,
        6.5620029e+03, 4.0548127e+03, 3.4556199e+03, 2.2674512e+03,
        1.7606123e+03, 1.3724764e+03, 9.8730164e+02, 8.5573792e+02,
        8.2189423e+02, 5.9744446e+02, 4.8068207e+02, 4.6329776e+02,
        3.7572604e+02, 3.5468460e+02, 3.4298883e+02, 3.3113547e+02,
        2.9915866e+02, 2.5318448e+02, 2.4073579e+02, 2.3217731e+02,
        1.9039682e+02, 1.7193799e+02, 1.6854317e+02, 1.5648985e+02,
        1.5593314e+02, 1.4361130e+02, 1.4090697e+02, 1.3636380e+02,
        1.2879050e+02, 1.2469593e+02, 1.1812107e+02, 1.0248475e+02,
        9.9281784e+01, 9.6250320e+01, 9.2002907e+01, 8.6321564e+01,
        7.7595932e+01, 7.6251175e+01, 7.2894218e+01, 6.7854935e+01,
        6.3795681e+01, 6.2841312e+01, 5.9735313e+01, 5.7088566e+01,
        5.6460163e+01, 5.6144310e+01], dtype=float32),
 'variance_ratio': array([4.891

In [69]:
adata.obsm['X_pca']

array([[-2.16924072e+02,  2.73957092e+02,  1.63952271e+02, ...,
        -1.61526699e+01,  3.16322970e+00,  4.71528143e-01],
       [-1.10486679e+02, -1.90206085e+02, -7.45063019e+01, ...,
         5.23604929e-01, -4.89958301e-02, -3.59555244e+00],
       [-2.04630070e+01, -2.58142975e+02,  1.69610962e+02, ...,
        -1.46209164e+01, -1.79227295e+01,  7.66218424e+00],
       ...,
       [-7.19943695e+01,  1.98386734e+02, -2.53583488e+01, ...,
        -9.35611916e+00, -5.10489988e+00,  6.66689694e-01],
       [-1.15791550e+02,  1.07714134e+02, -1.20059410e+02, ...,
         7.75037670e+00, -2.41459385e-01, -5.16630983e+00],
       [ 3.59034058e+02,  8.47824829e+02,  5.48739502e+02, ...,
         1.17725019e+01,  2.26474357e+00,  2.48942709e+00]], dtype=float32)

In [70]:
adata.obsm['X_pca'].shape

(11769, 50)

In [71]:
adata

AnnData object with n_obs × n_vars = 11769 × 33538
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes'
    var: 'gene_ids', 'feature_types', 'genome', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'pca'
    obsm: 'X_pca'
    varm: 'PCs'

In [73]:
adata.write_h5ad('/Users/sharmar1/Dropbox/msk_workshop/GSCN_2025/example_file.h5ad')

In [48]:
!pip install pandas

In [49]:
!pip install scikit-misc

In [50]:
!pip install colour

In [51]:
import colour

In [52]:
import colored